### ISSUE TITLE
Тестируйте не только размер

### ISSUE THREAD

**Issue by coursar** [sulaymonZafarov/priority#6]
https://github.com/sulaymonZafarov/priority/blob/91184ac5f711328b01794f84f84756ca59a2989e/main_test.go#L7-L30

Пример тестов для пустой очереди:
1. Создали - удостоверились, что размер 0
2. Добавили - удостоверились, что размер 1

Отрицательные проверки:
1. Попросили первый/последний у пустой очереди
2. Попросили удалить из пустой

Пример для очереди из одного элемента
1. Создали, добавили один элемент
2. Попросили первого/последнего - получили тот же элемент
3. Удалили первого - получили назад его же и удостоверились, что очередь стала пустой

И т.д. для очереди из нескольких элементов.

**Comment by ZSulaymon** [comment]
fixed:#6
